name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn
      - run: yarn build
      - run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
